chain:
    bech32_prefix: save
    modules: 
        - modules
        - messages
        - auth
        - bank
        - mint
        - upgrade
        - staking
        - feegrant
        - gov
        - actions
        - consensus
        - slashing
        - distribution
        - wasm
node:
    type: remote
    config:
        rpc:
            client_name: conversation
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: /home/ubuntu/.bdjuno/genesis.json
    average_block_time: 5s
database:
    url: postgres://postgres:postgres@localhost:5432/bdjuno?sslmode=disable&search_path=public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: save
          units:
            - denom: usave
              exponent: 0
            - denom: save
              exponent: 6
actions:
    host: 127.0.0.1
    port: 3000
    node:
        rpc:
            client_name: hasura-actions
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9090
            insecure: true
